
import Foundation

final class BreakViewModel {

    let babaBreakTasks: [(header: String, body: String)] = [
        ("How am I?",  "Oh, don't worry about me, poopsik.  It's you who I'm worried about."),
        ("You're too skinny!", "Do you want some of Baba's famous brownies?  Hold on, I'll get the recipe."),
        ("How's school?", "Wait, are you even still in school?  Oh, how time flies!"),
        ("You're so smart!", "Whatever you're working on, I'm sure you're doing great at it!"),
        ("My sweet poopsik.", "You are the light of my life.  You are so, so wonderful."),
        ("How's your break?", "I'm glad you're spending it with me.  Baba has missed her poopsik so."),
        ("What are you working on?", "Your Baba is here to help in any way she can."),
        ("You've grown!", "It seems like only yesterday when you were toddling around Baba's living room."),
        ("How are your friends?", "Are you still close with Andy?  How about Vicky?  Am I getting you confused with someone else?"),
        ("Thanks for visiting.", "It's so nice that you're here with Baba.  I'm so happy I can help you be productive."),
        ("...zzz...zzz", "Huh?  What?  No, no.  I was just resting my eyes..."),
        ("Smell that?", "Fresh cookies for Baba's wonderful poopsik!"),
        ("Busy?", "That's okay.  I don't mind if you need to go somewhere else for a little while."),
        ("Can I help?", "Even if it's just by cheering you on, I'd like to do something nice for you."),
        ("Need an ear?", "Poopsik, you know you can tell your Baba anything."),
        ("How are you?", "Hopefully you're happy as well as productive.  You know how I worry."),
        ("You're so pale!", "Why, there's no color in those cheeks at all.  Eat a big dinner tonight!"),
        ("La la-la-la la-la.", "Remember that pretty song we used to sing together?  La la-la-la la-la."),
        ("You're doing great!", "You've gotten so much done today.  I'm so proud of you!"),
        ("Baba loves you.", "Remember, poopsik.  No matter how hard it gets.  Your Baba loves you."),
        ("Don't push yourself.", "It's okay to take lots of breaks as long as you're doing your best."),
        ("You're such a blessing.", "Every minute you spend with your Baba is a blessing.  I love you, poopsik."),
        ("Stay for dinner?", "I made your favorite dish.  What is it?  Uh, it's your favorite, of course!"),
        ("Do your best.", "Do your best every day.  That's all anyone can do.  I believe in you, poopsik."),
        ("I hope you're well.", "All Baba needs to be happy is for her poopsik to be happy.  You're my entire world."),
        ("Something to drink?", "Ice water?  Iced tea?  Coffee?  Chocolate milk?  Seltzer?  Root beer?  Anything?"),
        ("How's your health?", "You seem a bit warm.  Take it easy, poopsik!  I hope you don't get sick."),
        ("You're so talented!", "You're so great at what you do.  Your Baba thinks you're just the best."),
        ("How's your sleep?", "At least eight hours a night, poopsik!  You need to take better care of yourself."),
        ("Thank you so much!", "Thank you so much for spending time with me today.  I know you're doing your best.")
    ]

    let popsBreakTasks: [(header: String, body: String)] = [
        ("Hard work pays off!", "I worked all my life to get where I am today, and I'm not done!"),
        ("It's about balance.", "Work hard, then rest up so you can work that much harder!"),
        ("Life isn't easy.", "Nothing is given to you.  You gotta work for it.  Never give up!"),
        ("Keep on learning.", "A perfect education gives you the information you need to accomplish your goals.  Nothing more, nothing less."),
        ("Treat others with respect.", "Everyone deserves respect until they demonstrate otherwise."),
        ("Keep up the momentum.", "Your goals aren't going to accomplish themselves.  Work, work, work!"),
        ("Complaining doesn't help.", "I know things can get really difficult, but never give in.  I'm here to help you work!"),
        ("Productivity is a mindset.", "How to get the most out of each of your days is something you should always be asking."),
        ("Youth is a gift.", "Don't waste it!  You only live through each stage of your life once."),
        ("Slacking?", "If you feel like procrastinating, just remember that it's only going to make tomorrow harder."),
        ("Not too hard.", "There's such a thing as being TOO hard on yourself, and that's not good for you either."),
        ("Enjoy the journey!", "Working toward your goals should be enjoyable.  If you dislike the process, perhaps you have the wrong goals."),
        ("Satisfied?", "That means you must have gotten a lot done today!  At least, I hope you did."),
        ("Limits.", "Everyone has their limits, and knowing them can help you grow beyond them."),
        ("Humanity.", "Never deny someone their humanity.  Everyone's journey is unique to them."),
        ("Take care of yourself.", "Proper diet, exercise, and sleep are the key elements in a productive life.  Don't neglect the basics!"),
        ("You'll never be perfect.", "There's no such thing.  But the pursuit of perfection can be a noble one."),
        ("Challenge yourself.", "Physically and mentally.  Every day.  An excess of comfort is not a good thing."),
        ("Back in my day...", "There was no internet or apps.  Only books.  So I read a bunch of them.  My point is, use the tools you got!"),
        ("Manage your stress.", "Turning into a big ball of anxiety helps no one.  Make sure to find time to decompress!"),
        ("Excuses.", "There are always a million reasons to not do what you need to do.  Do it anyway!"),
        ("You can do it.", "It may not seem like it, but I do believe in you.  Just no more excuses, okay?"),
        ("I'm not going anywhere.", "I'm right here with you.  And I'm going to make darn sure you keep working hard."),
        ("Losing confidence?", "Come back to it later with a fresh pair of eyes.  Sometimes a little perspective is all you need."),
        ("Values.", "Know your values and let them guide your actions.  There's no other way to live."),
        ("Giving up.", "It's not really quitting if you take what you learned and apply it to something even better."),
        ("Stay focused.", "The world can be a bizarre and scary place, but that just means there's plenty of work to be done."),
        ("Goals.", "Divide your time between short-term and long-term pursuits.  Minor victories are great, but there's nothing like fulfilling greater ambitions."),
        ("It's up to you.", "Don't let anyone tell you what you need for yourself.  Knowing yourself is the only way to be sure."),
        ("Asking for help.", "It's not a sign of weakness to receive assistance.  After all, that's what I'm here for!")
    ]

    let chadBreakTasks: [(header: String, body: String)] = [
        ("Do 10 Push Ups!",  "No... make it 15!  Strength in your arms is strength in your mind, bro!"),
        ("Bend over and touch your toes.",  "Count to 20.  Flexibility, bro, flexibility."),
        ("Breathing exercises!",  "Inhale for seven seconds, exhale for eleven.  Get that heart rate down, bro!"),
        ("15 crunches pronto!", "Otherwise you'll never amount to anything!  Trust me on this one."),
        ("Stay hydrated.", "Go get a glass of water.  You'll thank me later."),
        ("20 Jumping Jacks!", "Get your blood pumping!  It'll make you that much more productive."),
        ("Promise me something.", "You'll go for a jog later.  Promise me or I'll MAKE you promise me."),
        ("Exercise those legs!", "Gimme 20 squats right this minute, bro!  Don't be lazy!"),
        ("Sitting is for wimps!",  "Stand up for your next session.  I NEVER SIT!"),
        ("Do some pliés!",  "Don't know what those are?  Look it up, then.  THEN DO SOME!"),
        ("Shadow boxing time.",  "Imagine you're swinging at your past, wimpy self.  I'd swing at you, too!"),
        ("You getting enough nutrition?",  "Maybe you should order some protein powder or something."),
        ("Sleep is NOT for wimps.",  "Awesome people sleep a ton.  I'm awesome, so I sleep ALL THE TIME."),
        ("Calf stretch time!",  "Push yourself up onto your tiptoes 20 times.  Feel the burn, bro!"),
        ("You got any weights?",  "Well go lift them, then!  If not, then BUY SOME YOU WIMP."),
        ("Go get some fresh air.",  "And while you're out there why don't you jog around the block?"),
        ("You know what's fun?",  "Team sports.  You should look online for one to join."),
        ("Control your calories!",  "Split restaurant meal portions in half.  Two meals for the price of one!"),
        ("Fried Foods?",  "That stuff will clog your brain, bro.  That's the last thing YOU need."),
        ("Drinks with calories?",  "What are you, silly?  Stick to water, seltzer, coffee, and tea!"),
        ("Sit up straight!",  "How are you gonna lift later if your posture's all bent outta shape?"),
        ("Feeling stiff?",  "Sit on the floor with the bottoms of your feet pressed together.  That's the stuff, bro!"),
        ("Bored?",  "You should go rock climbing later this week.  That'll perk you right up!"),
        ("Bro...",  "Whatever excuse you're cooking up to get out of doing what you really should be doing.  STOP."),
        ("40 High Knees!",  "Jog in place while you count to 40.  Get those knees up!  HIGHER!!"),
        ("Clean your room!",  "A healthy environment reflects a healthy body and mind.  Didn't you know that?"),
        ("Had a massage lately?",  "Well, get one!  I've never felt so limber in my life.  Heck yeah, Bro!"),
        ("Check your heart rate.",  "Stress can mess with it.  Make sure you're taking care of yourself, bro."),
        ("Arm stretches!",  "Hold your arms straight out and rotate them forward 20 times then backwards 20 times."),
        ("No zero days!",  "You should move closer to one of your lifetime ambitions every day.  EVERY DAY, BRO!")
    ]
    
}
